<a href="https://colab.research.google.com/github/IndioP/Projeto_NLP/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import json
import os
!git clone https://github.com/IndioP/Projeto_NLP

Cloning into 'Projeto_NLP'...
remote: Enumerating objects: 208, done.
remote: Counting objects: 100% (208/208), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 208 (delta 186), reused 182 (delta 173), pack-reused 0
Receiving objects: 100% (208/208), 27.32 MiB | 17.48 MiB/s, done.
Resolving deltas: 100% (186/186), done.
Checking out files: 100% (183/183), done.


In [ ]:
data = list()
services_names = set()
for path_train in ['Projeto_NLP/files/train/','Projeto_NLP/files/test/','Projeto_NLP/files/dev/']:
  for file_name in os.listdir(path_train):
    with open(path_train+file_name, 'r') as f:
      data2 = json.load(f)
      for item in data2:
        for service in item['services']:
          services_names.add(service)
        
    
      data += data2


In [ ]:
#dando uma checada nos serviços do dataset
services_names

{'Alarm_1',
 'Banks_1',
 'Banks_2',
 'Buses_1',
 'Buses_2',
 'Buses_3',
 'Calendar_1',
 'Events_1',
 'Events_2',
 'Events_3',
 'Flights_1',
 'Flights_2',
 'Flights_3',
 'Flights_4',
 'Homes_1',
 'Homes_2',
 'Hotels_1',
 'Hotels_2',
 'Hotels_3',
 'Hotels_4',
 'Media_1',
 'Media_2',
 'Media_3',
 'Messaging_1',
 'Movies_1',
 'Movies_2',
 'Movies_3',
 'Music_1',
 'Music_2',
 'Music_3',
 'Payment_1',
 'RentalCars_1',
 'RentalCars_2',
 'RentalCars_3',
 'Restaurants_1',
 'Restaurants_2',
 'RideSharing_1',
 'RideSharing_2',
 'Services_1',
 'Services_2',
 'Services_3',
 'Services_4',
 'Trains_1',
 'Travel_1',
 'Weather_1'}

In [ ]:
print(len(data))

22825


In [ ]:
data = [item for item in data if ('Restaurants_1' in item['services'] or 'Restaurants_2' in item['services'])]

In [ ]:
print(len(data))

3218


In [ ]:
print(data[0])

{'dialogue_id': '60_00099', 'services': ['Events_1', 'Restaurants_1'], 'turns': [{'frames': [{'actions': [{'act': 'INFORM_INTENT', 'canonical_values': ['BuyEventTickets'], 'slot': 'intent', 'values': ['BuyEventTickets']}], 'service': 'Events_1', 'slots': [], 'state': {'active_intent': 'BuyEventTickets', 'requested_slots': [], 'slot_values': {}}}], 'speaker': 'USER', 'utterance': 'I am looking for tickets to an event.'}, {'frames': [{'actions': [{'act': 'REQUEST', 'canonical_values': [], 'slot': 'event_name', 'values': []}], 'service': 'Events_1', 'slots': []}], 'speaker': 'SYSTEM', 'utterance': 'Do you have a specific event in mind?'}, {'frames': [{'actions': [{'act': 'INFORM', 'canonical_values': ['Phutureprimitive'], 'slot': 'event_name', 'values': ['Phutureprimitive']}, {'act': 'INFORM', 'canonical_values': ['3'], 'slot': 'number_of_seats', 'values': ['3']}], 'service': 'Events_1', 'slots': [{'exclusive_end': 46, 'slot': 'event_name', 'start': 30}], 'state': {'active_intent': 'BuyEv

In [ ]:
print(json.dumps(data[0], indent=4, sort_keys=True))

{
    "dialogue_id": "60_00099",
    "services": [
        "Events_1",
        "Restaurants_1"
    ],
    "turns": [
        {
            "frames": [
                {
                    "actions": [
                        {
                            "act": "INFORM_INTENT",
                            "canonical_values": [
                                "BuyEventTickets"
                            ],
                            "slot": "intent",
                            "values": [
                                "BuyEventTickets"
                            ]
                        }
                    ],
                    "service": "Events_1",
                    "slots": [],
                    "state": {
                        "active_intent": "BuyEventTickets",
                        "requested_slots": [],
                        "slot_values": {}
                    }
                }
            ],
            "speaker": "USER",
            "utterance": "I am l

In [ ]:
print(json.dumps(data[0]['turns'][0], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM_INTENT",
                    "canonical_values": [
                        "BuyEventTickets"
                    ],
                    "slot": "intent",
                    "values": [
                        "BuyEventTickets"
                    ]
                }
            ],
            "service": "Events_1",
            "slots": [],
            "state": {
                "active_intent": "BuyEventTickets",
                "requested_slots": [],
                "slot_values": {}
            }
        }
    ],
    "speaker": "USER",
    "utterance": "I am looking for tickets to an event."
}


Separando um dataframe somente com os somentarios do usuarios para usarmos no na classificação de intenção

In [ ]:
data3 = list()
for item in data:
  for turn in item['turns']:
    if(turn['speaker'] == 'USER'):
      #has_restaurant_frame = False
      #for frame in turn['frames']:
      #  if(frame['service'] == 'Restaurants_1' or frame['service'] == 'Restaurants_2'):
      #    has_restaurant_frame = True
      #if(has_restaurant_frame):
      data3.append(turn)
data = data3

In [ ]:
print(len(data))

38465


In [ ]:
print(json.dumps(data[0], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM_INTENT",
                    "canonical_values": [
                        "BuyEventTickets"
                    ],
                    "slot": "intent",
                    "values": [
                        "BuyEventTickets"
                    ]
                }
            ],
            "service": "Events_1",
            "slots": [],
            "state": {
                "active_intent": "BuyEventTickets",
                "requested_slots": [],
                "slot_values": {}
            }
        }
    ],
    "speaker": "USER",
    "utterance": "I am looking for tickets to an event."
}


In [ ]:
print(json.dumps(data[1], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM",
                    "canonical_values": [
                        "Phutureprimitive"
                    ],
                    "slot": "event_name",
                    "values": [
                        "Phutureprimitive"
                    ]
                },
                {
                    "act": "INFORM",
                    "canonical_values": [
                        "3"
                    ],
                    "slot": "number_of_seats",
                    "values": [
                        "3"
                    ]
                }
            ],
            "service": "Events_1",
            "slots": [
                {
                    "exclusive_end": 46,
                    "slot": "event_name",
                    "start": 30
                }
            ],
            "state": {
                "active_intent": "BuyEventTickets",
                "

Separando somente as informações que são relacionadas ao dominio ao qual iremos trabalhar, que é o de RESTAURANTES

In [ ]:
data3 = list()
for item in data:
  frame_has_restaurants = False
  for frame in item['frames']:
    if(frame['service'] == 'Restaurants_1' or frame['service'] == 'Restaurants_2'):
      frame_has_restaurants = True
  if frame_has_restaurants:
    data3.append(item)
data = data3

In [ ]:
data[5]

{'frames': [{'actions': [{'act': 'INFORM',
     'canonical_values': ['moderate'],
     'slot': 'price_range',
     'values': ['moderate']},
    {'act': 'INFORM',
     'canonical_values': ['Mexican'],
     'slot': 'cuisine',
     'values': ['Tacos']},
    {'act': 'INFORM_INTENT',
     'canonical_values': ['FindRestaurants'],
     'slot': 'intent',
     'values': ['FindRestaurants']}],
   'service': 'Restaurants_1',
   'slots': [{'exclusive_end': 68, 'slot': 'cuisine', 'start': 63}],
   'state': {'active_intent': 'FindRestaurants',
    'requested_slots': [],
    'slot_values': {'city': ['Oakland'],
     'cuisine': ['Tacos'],
     'price_range': ['moderate']}}}],
 'speaker': 'USER',
 'utterance': 'Yes, I also want to find an afforadable restaurant that offers Tacos.'}

In [ ]:
for item in data:
  item['frames'] = [frame for frame in item['frames'] if (frame['service'] == 'Restaurants_1' or frame['service'] == 'Restaurants_2')]

In [ ]:
print(json.dumps(item, indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "THANK_YOU",
                    "canonical_values": [],
                    "slot": "",
                    "values": []
                },
                {
                    "act": "GOODBYE",
                    "canonical_values": [],
                    "slot": "",
                    "values": []
                }
            ],
            "service": "Restaurants_2",
            "slots": [],
            "state": {
                "active_intent": "ReserveRestaurant",
                "requested_slots": [],
                "slot_values": {
                    "category": [
                        "Oriental"
                    ],
                    "date": [
                        "3rd of March",
                        "day after tomorrow"
                    ],
                    "location": [
                        "Orinda"
                    ],
                    "number_o

In [ ]:
print(json.dumps(data[0], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM",
                    "canonical_values": [
                        "Japanese"
                    ],
                    "slot": "cuisine",
                    "values": [
                        "Izakaya"
                    ]
                },
                {
                    "act": "INFORM_INTENT",
                    "canonical_values": [
                        "FindRestaurants"
                    ],
                    "slot": "intent",
                    "values": [
                        "FindRestaurants"
                    ]
                }
            ],
            "service": "Restaurants_1",
            "slots": [
                {
                    "exclusive_end": 61,
                    "slot": "cuisine",
                    "start": 54
                }
            ],
            "state": {
                "active_intent": "FindRestaurants",
         

Identificando os ACTIONS que estão no dataset

In [ ]:
for item in data:
  #item["intent"] = item['frames'][0]['state']['active_intent']
  #item.pop('speaker', None)
  #item.pop('frames', None)
  item["intent"] = []
  for intent in item['frames'][0]['actions']:
    item["intent"] += [intent['act']]

In [ ]:
for item in data:
  intents = list()
  for intent in item['intent']:
    if (intent == 'INFORM_INTENT'):
      intent = item['frames'][0]['state']['active_intent']
    intents.append(intent)
    
  item['intent'] = intents
  #print(item['intent'])

In [ ]:
for item in data:
  item.pop('speaker', None)
  item.pop('frames', None)

In [ ]:
data[0]

{'intent': ['INFORM', 'FindRestaurants'],
 'utterance': 'Good. I also need to find a restaurant. Are there any Izakaya places near there?'}

In [ ]:
intents = set()
for item in data:
  for intent in item['intent']:
    intents.add(intent)
print(intents)
num_classes = len(intents)
print(len(intents))

{'REQUEST', 'AFFIRM', 'NEGATE', 'GOODBYE', 'SELECT', 'THANK_YOU', 'REQUEST_ALTS', 'ReserveRestaurant', 'FindRestaurants', 'AFFIRM_INTENT', 'NEGATE_INTENT', 'INFORM'}
12


In [ ]:
import pandas as pd
utterances = [item['utterance'] for item in data]
df = pd.DataFrame({"utterance":utterances})

In [ ]:
df

utterance
0      Good. I also need to find a restaurant. Are th...
1      Is the price range above average? What's the a...
2                                 Yes, that sounds good.
3                                   No, not now. Thanks.
4                                        No, that's all.
...                                                  ...
23419                             Ok, that will be good.
23420  Yes, I would like to reserve a table for the 3...
23421       Yes, please make it for in the evening 6:45.
23422   Yes, perfect, can you give me their user rating?
23423             Thank you, that is all I need for now.

[23424 rows x 1 columns]

In [ ]:
intents

{'AFFIRM',
 'AFFIRM_INTENT',
 'FindRestaurants',
 'GOODBYE',
 'INFORM',
 'NEGATE',
 'NEGATE_INTENT',
 'REQUEST',
 'REQUEST_ALTS',
 'ReserveRestaurant',
 'SELECT',
 'THANK_YOU'}

In [ ]:
for intent in intents:
  df[intent] = 0
  df['Others'] = 0
df.head()

utterance  ...  INFORM
0  Good. I also need to find a restaurant. Are th...  ...       0
1  Is the price range above average? What's the a...  ...       0
2                             Yes, that sounds good.  ...       0
3                               No, not now. Thanks.  ...       0
4                                    No, that's all.  ...       0

[5 rows x 14 columns]

In [ ]:
for i in range(len(data)):
  for intent in data[i]['intent']:

    if 'FindRestaurants' in data[i]['intent']:
      df.loc[i, 'FindRestaurants'] = 1
    elif 'ReserveRestaurant' in data[i]['intent']:
      df.loc[i, 'ReserveRestaurant'] = 1
    else:
      df.loc[i, 'Others'] = 1

In [ ]:
df[df['ReserveRestaurant'] == 1].head()

utterance  ...  INFORM
729                   I need a restaurant reservation.  ...       0
735  On March 2nd we are going to celebrate my wedd...  ...       0
741  id like to make a reservation for friday next ...  ...       0
746  I would like to make a reservation at the rest...  ...       0
753      I want to make a reservation at a restaurant.  ...       0

[5 rows x 14 columns]

In [ ]:
df[df['Others'] != 0].head(10)

utterance  ...  INFORM
1   Is the price range above average? What's the a...  ...       0
2                              Yes, that sounds good.  ...       0
3                                No, not now. Thanks.  ...       0
4                                     No, that's all.  ...       0
6                            is alcohol served there?  ...       0
7                  Can you suggest me someplace else?  ...       0
8                  Yes, that works. That would be all  ...       0
10                                 Let's do Sicilian.  ...       0
11                                 That works for me.  ...       0
12                        Not yet, that's it for now.  ...       0

[10 rows x 14 columns]

In [ ]:
#Dessa forma, podemos reduzir um pouco o escopo e manter uma classificação com apenas 3 classes, sendo a Others, com o valor '1' quando qualquer outro valor
#     diferente de FindRestaurants e ReserveRestaurant
df = df[['utterance','FindRestaurants','ReserveRestaurant','Others']]

In [ ]:
df.head(5)

utterance  ...  Others
0  Good. I also need to find a restaurant. Are th...  ...       0
1  Is the price range above average? What's the a...  ...       1
2                             Yes, that sounds good.  ...       1
3                               No, not now. Thanks.  ...       1
4                                    No, that's all.  ...       1

[5 rows x 4 columns]

In [ ]:
df.count()

utterance            23424
FindRestaurants      23424
ReserveRestaurant    23424
Others               23424
dtype: int64

In [ ]:
df.sum()

utterance            Good. I also need to find a restaurant. Are th...
FindRestaurants                                                   2717
ReserveRestaurant                                                 2090
Others                                                           18617
dtype: object

Como o dataset está bem desbalanceado, precisamos fazer um reajuste nele para podermos equilibrar as coisas

In [ ]:
df.head(5)

utterance  ...  Others
0  Good. I also need to find a restaurant. Are th...  ...       0
1  Is the price range above average? What's the a...  ...       1
2                             Yes, that sounds good.  ...       1
3                               No, not now. Thanks.  ...       1
4                                    No, that's all.  ...       1

[5 rows x 4 columns]

In [ ]:
others = df[df['Others'] == 1]
not_others = df[df['Others'] == 0]
others = others.sample(frac = 1)
others.sum()


utterance            Yes, that would be great.I need the reservatio...
FindRestaurants                                                      0
ReserveRestaurant                                                    0
Others                                                           18617
dtype: object

In [ ]:
others = others.iloc[:2500,:]
others.sum()

utterance            Yes, that would be great.I need the reservatio...
FindRestaurants                                                      0
ReserveRestaurant                                                    0
Others                                                            2500
dtype: object

In [ ]:
not_others.sum()

utterance            Good. I also need to find a restaurant. Are th...
FindRestaurants                                                   2717
ReserveRestaurant                                                 2090
Others                                                               0
dtype: object

In [ ]:
df = others.append(not_others)
df.sum()
df = df.sample(frac = 1)

#Iniciando a Classificação

In [17]:
import matplotlib.pyplot as plt
import re
import shutil
import string
import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
from tensorflow.keras import losses
from tensorflow.keras import preprocessing

In [ ]:
def custom_standardization(input_data):
  lowercase = tf.strings.lower(input_data)
  stripped_html = tf.strings.regex_replace(lowercase, '<br />', ' ')
  return tf.strings.regex_replace(stripped_html,
                                  '[%s]' % re.escape(string.punctuation),
                                  '')

In [ ]:
max_features = 10000
sequence_length = 250

vectorize_layer = layers.TextVectorization(
    standardize=custom_standardization,
    max_tokens=max_features,
    output_mode='int',
    output_sequence_length=sequence_length)

In [ ]:
dd = df.to_dict(orient="list")

In [ ]:
df

utterance  ...  Others
21477  Where can I dine with a vegetarian choices on ...  ...       0
22296                                       thanks a lot  ...       1
1256              I want a reservation for a restaurant.  ...       0
12728  I am meeting friends and would like to find a ...  ...       0
17275    I'd like to find a restaurant there too please.  ...       0
...                                                  ...  ...     ...
16208                 Yes, also do they have live music?  ...       1
5854                       I would like to eat somewhere  ...       0
22180                                         ok perfect  ...       1
14530  Oh yeah, I've heard good things about Red Joan...  ...       0
13762                     How about in the evening 7:45?  ...       1

[7307 rows x 4 columns]

Teste de vetorização de um texto

In [ ]:
train_text = [x['utterance'] for x in data]
train_labels = [y['intent'] for y in data]
vectorize_layer.adapt(train_text)

In [ ]:
def vectorize_text(text):
  #text = tf.expand_dims(text, -1)
  return vectorize_layer(text)

In [ ]:
first_review = train_text[0]
first_label = train_labels[0]
print("Review", first_review)
#print("Label", raw_train_ds.class_names[first_label])
print("Label", first_label)
print("Vectorized review", vectorize_text(first_review))

Review Good. I also need to find a restaurant. Are there any Izakaya places near there?
Label ['INFORM', 'FindRestaurants']
Vectorized review tf.Tensor(
[ 31   3  52  42   5  17   2  12  66  16  78 295 200 207  16   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0

In [ ]:
print('Vocabulary size: {}'.format(len(vectorize_layer.get_vocabulary())))

Vocabulary size: 3054


Criando a REDE

In [ ]:
embedding_dim = 16

model = tf.keras.Sequential([
  layers.Embedding(max_features + 1, embedding_dim),
  layers.Dropout(0.2),
  layers.GlobalAveragePooling1D(),
  layers.Dropout(0.2),
  #layers.SpatialDropout1D(0.2),
  #layers.LSTM(200, dropout=0.2, recurrent_dropout=0.2),
  layers.Dense(50),
  layers.Dense(3, activation='softmax')])

model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, None, 16)          160016    
_________________________________________________________________
dropout_6 (Dropout)          (None, None, 16)          0         
_________________________________________________________________
global_average_pooling1d_3 ( (None, 16)                0         
_________________________________________________________________
dropout_7 (Dropout)          (None, 16)                0         
_________________________________________________________________
dense_5 (Dense)              (None, 50)                850       
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 153       
Total params: 161,019
Trainable params: 161,019
Non-trainable params: 0
________________________________________________

In [ ]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [ ]:
train_text = df['utterance'].tolist()
X_train = tf.convert_to_tensor([vectorize_text(utterance) for utterance in train_text])

In [ ]:
X_train

<tf.Tensor: shape=(7307, 250), dtype=int64, numpy=
array([[113,  15,   3, ...,   0,   0,   0],
       [ 18,   2,  90, ...,   0,   0,   0],
       [  3,  23,   2, ...,   0,   0,   0],
       ...,
       [114,  60,   0, ...,   0,   0,   0],
       [325, 112, 345, ...,   0,   0,   0],
       [ 99, 117,  11, ...,   0,   0,   0]])>

In [ ]:
Y_train = df.loc[:, df.columns != 'utterance']
Y_train = tf.convert_to_tensor(Y_train)
Y_train

<tf.Tensor: shape=(7307, 3), dtype=int64, numpy=
array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       ...,
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1]])>

Treinando o modelo

In [ ]:
epochs = 20
batch_size = 64

history = model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size,validation_split=0.1)

Epoch 1/20
103/103 [==============================] - 2s 10ms/step - loss: 1.0916 - accuracy: 0.3755 - val_loss: 1.0874 - val_accuracy: 0.3502
Epoch 2/20
103/103 [==============================] - 1s 8ms/step - loss: 1.0791 - accuracy: 0.4066 - val_loss: 1.0629 - val_accuracy: 0.3557
Epoch 3/20
103/103 [==============================] - 1s 8ms/step - loss: 1.0152 - accuracy: 0.5509 - val_loss: 0.9371 - val_accuracy: 0.7756
Epoch 4/20
103/103 [==============================] - 1s 8ms/step - loss: 0.8101 - accuracy: 0.7915 - val_loss: 0.6669 - val_accuracy: 0.8495
Epoch 5/20
103/103 [==============================] - 1s 8ms/step - loss: 0.5567 - accuracy: 0.8669 - val_loss: 0.4539 - val_accuracy: 0.8865
Epoch 6/20
103/103 [==============================] - 1s 8ms/step - loss: 0.4098 - accuracy: 0.8843 - val_loss: 0.3703 - val_accuracy: 0.9015
Epoch 7/20
103/103 [==============================] - 1s 8ms/step - loss: 0.3348 - accuracy: 0.9009 - val_loss: 0.3045 - val_accuracy: 0.9083
Epoch

#Extraction

Processando os dados novamente

In [2]:
data = list()
services_names = set()
for path_train in ['Projeto_NLP/files/train/','Projeto_NLP/files/test/','Projeto_NLP/files/dev/']:
  for file_name in os.listdir(path_train):
    with open(path_train+file_name, 'r') as f:
      data2 = json.load(f)
      for item in data2:
        for service in item['services']:
          services_names.add(service)
        
    
      data += data2

In [3]:
data = [item for item in data if ('Restaurants_1' in item['services'] or 'Restaurants_2' in item['services'])]

In [4]:
print(data[0])

{'dialogue_id': '107_00097', 'services': ['Media_1', 'Restaurants_1'], 'turns': [{'frames': [{'actions': [{'act': 'INFORM_INTENT', 'canonical_values': ['FindMovies'], 'slot': 'intent', 'values': ['FindMovies']}], 'service': 'Media_1', 'slots': [], 'state': {'active_intent': 'FindMovies', 'requested_slots': [], 'slot_values': {}}}], 'speaker': 'USER', 'utterance': 'I am in a mood for films. Search for online movies.'}, {'frames': [{'actions': [{'act': 'REQUEST', 'canonical_values': [], 'slot': 'genre', 'values': []}], 'service': 'Media_1', 'slots': []}], 'speaker': 'SYSTEM', 'utterance': 'What type of movies shall I find you?'}, {'frames': [{'actions': [{'act': 'INFORM', 'canonical_values': ['Drama'], 'slot': 'genre', 'values': ['Drama']}], 'service': 'Media_1', 'slots': [{'exclusive_end': 15, 'slot': 'genre', 'start': 10}], 'state': {'active_intent': 'FindMovies', 'requested_slots': [], 'slot_values': {'genre': ['Drama']}}}], 'speaker': 'USER', 'utterance': 'I am into Drama movies.'}, 

In [5]:
data3 = list()
for item in data:
  for turn in item['turns']:
    if(turn['speaker'] == 'USER'):
      #has_restaurant_frame = False
      #for frame in turn['frames']:
      #  if(frame['service'] == 'Restaurants_1' or frame['service'] == 'Restaurants_2'):
      #    has_restaurant_frame = True
      #if(has_restaurant_frame):
      data3.append(turn)
data = data3

In [6]:
print(data[0])

{'frames': [{'actions': [{'act': 'INFORM_INTENT', 'canonical_values': ['FindMovies'], 'slot': 'intent', 'values': ['FindMovies']}], 'service': 'Media_1', 'slots': [], 'state': {'active_intent': 'FindMovies', 'requested_slots': [], 'slot_values': {}}}], 'speaker': 'USER', 'utterance': 'I am in a mood for films. Search for online movies.'}


In [7]:
data3 = list()
for item in data:
  frame_has_restaurants = False
  for frame in item['frames']:
    if(frame['service'] == 'Restaurants_1' or frame['service'] == 'Restaurants_2'):
      frame_has_restaurants = True
  if frame_has_restaurants:
    data3.append(item)
data = data3

In [8]:
for item in data:
  item['frames'] = [frame for frame in item['frames'] if (frame['service'] == 'Restaurants_1' or frame['service'] == 'Restaurants_2')]

Visualização geral do Dataset e a estrtura dos 'utterance' com as frases utilizadas pelos USUARIOS e os SLOT's

In [9]:
print(json.dumps(data[9], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM",
                    "canonical_values": [
                        "10:45"
                    ],
                    "slot": "time",
                    "values": [
                        "10:45"
                    ]
                },
                {
                    "act": "INFORM",
                    "canonical_values": [
                        "Hardwood Bar & Smokery"
                    ],
                    "slot": "restaurant_name",
                    "values": [
                        "Hardwood Bar & Smokery"
                    ]
                }
            ],
            "service": "Restaurants_1",
            "slots": [
                {
                    "exclusive_end": 17,
                    "slot": "time",
                    "start": 12
                },
                {
                    "exclusive_end": 47,
                    "slot": "resta

In [10]:
count = 0
for item in data:
  if(len(item['frames']) == 1):
    count+=1
print(count)
print(len(data))

23424
23424


Separando as FRASES e os SLOTs relacionados a elas

In [11]:
data3 = []
for item in data:
  data3.append([item['utterance'], item['frames'][0]['slots']])
print(data3)

[['Thank you. Book me a restaurant around that place.', []], ["Book me Pasquale's restaurant in SF for 16:30.", [{'exclusive_end': 45, 'slot': 'time', 'start': 40}, {'exclusive_end': 35, 'slot': 'city', 'start': 33}, {'exclusive_end': 18, 'slot': 'restaurant_name', 'start': 8}]], ['That will be perfect.', []], ['Nope. Thanks anyway.', []], ['I want to make a restaurant reservation in this area.', []], ['It is for four. Have it start at 6:30 pm at Picnic on Third in San Francisco.', [{'exclusive_end': 40, 'slot': 'time', 'start': 33}, {'exclusive_end': 76, 'slot': 'city', 'start': 63}, {'exclusive_end': 59, 'slot': 'restaurant_name', 'start': 44}]], ['Yes, that is good. Is it expensive? What is the address?', []], ['No, that is all.', []], ['Thank you! I want to make a reservation at a restaurant.', []], ['Make it for 10:45 at the Hardwood Bar & Smokery.', [{'exclusive_end': 17, 'slot': 'time', 'start': 12}, {'exclusive_end': 47, 'slot': 'restaurant_name', 'start': 25}]], ['In San Fran.

- Fazendo a separação das FRASES e separando as PALAVRAS por todos os seus CARACTERES para ajudar na analise da REDE
- Depois disso, cada CARACTER relacionado a PALAVRA que possui a relação com a categoria do SLOT (seja City, Date, Restaurant name, etc...), possui uma relação em outra lista com a posição desses caracteres e essas palavras dos SLOTS

In [12]:

data = []
for item in data3:
  tags = ['O' for _ in range(len(item[0]))]
  for slot in item[1]:
    for i in range(slot['start'],slot['exclusive_end']):
      tags[i] = slot['slot']
  data.append([list(item[0]), tags])

In [13]:
print(data[1])

[['B', 'o', 'o', 'k', ' ', 'm', 'e', ' ', 'P', 'a', 's', 'q', 'u', 'a', 'l', 'e', "'", 's', ' ', 'r', 'e', 's', 't', 'a', 'u', 'r', 'a', 'n', 't', ' ', 'i', 'n', ' ', 'S', 'F', ' ', 'f', 'o', 'r', ' ', '1', '6', ':', '3', '0', '.'], ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'restaurant_name', 'restaurant_name', 'restaurant_name', 'restaurant_name', 'restaurant_name', 'restaurant_name', 'restaurant_name', 'restaurant_name', 'restaurant_name', 'restaurant_name', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'city', 'city', 'O', 'O', 'O', 'O', 'O', 'time', 'time', 'time', 'time', 'time', 'O']]


Criando uma relação dos CARACTERES com um NÚMERO para ajudar no treinamento na REDE

In [14]:
import numpy as np
all_text = " ".join([" ".join(x[0]) for x in data])
vocab = sorted(set(all_text))

labels = set()
for item in data:
  for tags in item[1]:
    labels.add(tags)
#labels = sorted(labels)
# create character/id and label/id mapping
char2idx = {u:i+1 for i, u in enumerate(vocab)}
idx2char = np.array(vocab)
label2idx = {u:i+1 for i, u in enumerate(labels)}
idx2label = np.array(labels)
    
print(idx2label)
print(char2idx)

{'location', 'city', 'category', 'date', 'O', 'cuisine', 'restaurant_name', 'time'}
{' ': 1, '!': 2, '"': 3, '#': 4, '&': 5, "'": 6, '(': 7, ')': 8, ',': 9, '-': 10, '.': 11, '/': 12, '0': 13, '1': 14, '2': 15, '3': 16, '4': 17, '5': 18, '6': 19, '7': 20, '8': 21, '9': 22, ':': 23, ';': 24, '?': 25, 'A': 26, 'B': 27, 'C': 28, 'D': 29, 'E': 30, 'F': 31, 'G': 32, 'H': 33, 'I': 34, 'J': 35, 'K': 36, 'L': 37, 'M': 38, 'N': 39, 'O': 40, 'P': 41, 'Q': 42, 'R': 43, 'S': 44, 'T': 45, 'U': 46, 'V': 47, 'W': 48, 'X': 49, 'Y': 50, 'Z': 51, '`': 52, 'a': 53, 'b': 54, 'c': 55, 'd': 56, 'e': 57, 'f': 58, 'g': 59, 'h': 60, 'i': 61, 'j': 62, 'k': 63, 'l': 64, 'm': 65, 'n': 66, 'o': 67, 'p': 68, 'q': 69, 'r': 70, 's': 71, 't': 72, 'u': 73, 'v': 74, 'w': 75, 'x': 76, 'y': 77, 'z': 78}


Relacionado as LISTAS de CARACTERES que foram criadas anteriormente com as frases dos USUARIOS, com a relação de CADA CARACTER com um NÚMERO

In [15]:
import random 

def split_char_labels(eg):
  tokens = eg[0]
  labels=eg[1]

  input_chars = []
  output_char_labels = []

  for token,label in zip(tokens,labels):

    input_chars.extend([char for char in token])
    input_chars.extend(' ')
    output_char_labels.extend([label]*len(token))
    output_char_labels.extend('O')

  return [
          [char2idx[x] for x in input_chars[:-1]],
          np.array([label2idx[x] for x in output_char_labels[:-1]])
          ]

train_formatted = [split_char_labels(eg) for eg in data]

DATASET_SIZE = len(train_formatted)

val_size = int(0.15 * DATASET_SIZE)
test_size = int(0.15 * DATASET_SIZE)

random.shuffle(train_formatted)

test_formatted = train_formatted[0:val_size]
train_fomatted = train_formatted[val_size:test_size]
val_formatted = train_formatted[val_size+test_size:]


print(len(train_formatted))
print(train_formatted[0])

23424
[[26, 1, 1, 1, 68, 1, 64, 1, 53, 1, 55, 1, 57, 1, 1, 1, 75, 1, 60, 1, 61, 1, 55, 1, 60, 1, 1, 1, 71, 1, 57, 1, 70, 1, 74, 1, 57, 1, 71, 1, 1, 1, 41, 1, 61, 1, 78, 1, 78, 1, 53, 1, 1, 1, 53, 1, 66, 1, 56, 1, 1, 1, 41, 1, 53, 1, 71, 1, 72, 1, 53, 1, 1, 1, 61, 1, 71, 1, 1, 1, 58, 1, 61, 1, 66, 1, 57, 1, 11], array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5,
       3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5, 3, 5,
       3, 5, 3, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5])]


In [18]:
    # training generator
    def gen_train_series():

        for eg in train_formatted:
          yield eg[0],eg[1]
    
    # validation generator
    def gen_valid_series():
    
       for eg in val_formatted:
          yield eg[0],eg[1]
    
    # test generator
    def gen_test_series():

      for eg in test_formatted:
          yield eg[0],eg[1]
      
    # create Dataset objects for train, test and validation sets  
    series = tf.data.Dataset.from_generator(gen_train_series,output_types=(tf.int32, tf.int32),output_shapes = ((None, None)))
    series_valid = tf.data.Dataset.from_generator(gen_valid_series,output_types=(tf.int32, tf.int32),output_shapes = ((None, None)))
    series_test = tf.data.Dataset.from_generator(gen_test_series,output_types=(tf.int32, tf.int32),output_shapes = ((None, None)))

    BATCH_SIZE = 128
    BUFFER_SIZE=1000
    
    # create padded batch series objects for train, test and validation sets
    ds_series_batch = series.shuffle(BUFFER_SIZE).padded_batch(BATCH_SIZE, padded_shapes=([None], [None]), drop_remainder=True)
    ds_series_batch_valid = series_valid.padded_batch(BATCH_SIZE, padded_shapes=([None], [None]), drop_remainder=True)
    ds_series_batch_test = series_test.padded_batch(BATCH_SIZE, padded_shapes=([None], [None]), drop_remainder=True)
    
    # print example batches
    for input_example_batch, target_example_batch in ds_series_batch_valid.take(1):
      print(input_example_batch)
      print(target_example_batch)


tf.Tensor(
[[34  1  1 ...  0  0  0]
 [45  1 60 ...  0  0  0]
 [38  1 77 ...  0  0  0]
 ...
 [50  1 57 ...  0  0  0]
 [45  1 60 ...  0  0  0]
 [32  1 70 ...  0  0  0]], shape=(128, 229), dtype=int32)
tf.Tensor(
[[5 5 5 ... 0 0 0]
 [5 5 5 ... 0 0 0]
 [5 5 5 ... 0 0 0]
 ...
 [5 5 5 ... 0 0 0]
 [5 5 5 ... 0 0 0]
 [5 5 5 ... 0 0 0]], shape=(128, 229), dtype=int32)


Preparando os parametros utilizados pela REDE relacionados ao tamanho do vocabulario do DOMINIO e criando a REDE LSTM

In [19]:
vocab_size = len(vocab)+1

# The embedding dimension
embedding_dim = 256

# Number of RNN units
rnn_units = 1024

label_size = len(labels)  

# build LSTM model
def build_model(vocab_size,label_size, embedding_dim, rnn_units, batch_size):
      model = tf.keras.Sequential([
          tf.keras.layers.Embedding(vocab_size, embedding_dim,
                            batch_input_shape=[batch_size, None],mask_zero=True),
          tf.keras.layers.LSTM(rnn_units,
                      return_sequences=True,
                      stateful=True,
                      recurrent_initializer='glorot_uniform'),
          tf.keras.layers.Dense(label_size)
          ])
      return model

model = build_model(
      vocab_size = len(vocab)+1,
      label_size=len(labels)+1,
      embedding_dim=embedding_dim,
      rnn_units=rnn_units,
      batch_size=BATCH_SIZE)

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (128, None, 256)          20224     
                                                                 
 lstm (LSTM)                 (128, None, 1024)         5246976   
                                                                 
 dense (Dense)               (128, None, 9)            9225      
                                                                 
Total params: 5,276,425
Trainable params: 5,276,425
Non-trainable params: 0
_________________________________________________________________


In [20]:
import os

# define loss function
def loss(labels, logits):
    return tf.keras.losses.sparse_categorical_crossentropy(labels, logits, from_logits=True)

model.compile(optimizer='adam', loss=loss,metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])

# Directory where the checkpoints will be saved
checkpoint_dir = './training_checkpoints'
# Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)

In [21]:
EPOCHS=10
history = model.fit(ds_series_batch, epochs=EPOCHS, validation_data=ds_series_batch_valid,callbacks=[checkpoint_callback])

Epoch 1/10
183/183 [==============================] - 121s 612ms/step - loss: 0.0705 - sparse_categorical_accuracy: 0.9485 - val_loss: 0.0547 - val_sparse_categorical_accuracy: 0.9567
Epoch 2/10
183/183 [==============================] - 111s 603ms/step - loss: 0.0554 - sparse_categorical_accuracy: 0.9553 - val_loss: 0.0440 - val_sparse_categorical_accuracy: 0.9611
Epoch 3/10
183/183 [==============================] - 111s 608ms/step - loss: 0.0419 - sparse_categorical_accuracy: 0.9612 - val_loss: 0.0372 - val_sparse_categorical_accuracy: 0.9630
Epoch 4/10
183/183 [==============================] - 111s 605ms/step - loss: 0.0378 - sparse_categorical_accuracy: 0.9634 - val_loss: 0.0372 - val_sparse_categorical_accuracy: 0.9641
Epoch 5/10
183/183 [==============================] - 111s 603ms/step - loss: 0.0343 - sparse_categorical_accuracy: 0.9670 - val_loss: 0.0302 - val_sparse_categorical_accuracy: 0.9709
Epoch 6/10
183/183 [==============================] - 111s 604ms/step - loss: 0.

Visualização final das relações das palavras do DOMINIO que pegamos dos SLOTs

In [22]:
from sklearn.metrics import classification_report, confusion_matrix

preds = np.array([])
y_trues= np.array([])

# iterate through test set, make predictions based on trained model
for input_example_batch, target_example_batch in ds_series_batch_test:

  pred=model.predict_on_batch(input_example_batch)
  pred_max=tf.argmax(tf.nn.softmax(pred),2).numpy().flatten()
  y_true=target_example_batch.numpy().flatten()

  preds=np.concatenate([preds,pred_max])
  y_trues=np.concatenate([y_trues,y_true])

# remove padding from evaluation
remove_padding = [(p,y) for p,y in zip(preds,y_trues) if y!=0]

r_p = [x[0] for x in remove_padding]
r_t = [x[1] for x in remove_padding]

# print confusion matrix and classification report
print(confusion_matrix(r_p,r_t))
print(classification_report(r_p,r_t))

[[    51     47      6      0      3      6      0      0]
 [   497   1188      6      0     31     16      5      2]
 [     0      0     13      0      0      2      0      0]
 [     0      0      0   1128    117      2     13      4]
 [    70    226    201    214 275259    851    263    348]
 [    10     38    647      6    305   1605    135      0]
 [     0     28      7     24    124     12    544      8]
 [     0      2      0     10    264      4      5   6013]]
              precision    recall  f1-score   support

         1.0       0.08      0.45      0.14       113
         2.0       0.78      0.68      0.73      1745
         3.0       0.01      0.87      0.03        15
         4.0       0.82      0.89      0.85      1264
         5.0       1.00      0.99      0.99    277432
         6.0       0.64      0.58      0.61      2746
         7.0       0.56      0.73      0.64       747
         8.0       0.94      0.95      0.95      6298

    accuracy                           