In [1]:
import json
import os
!git clone https://github.com/IndioP/Projeto_NLP

Cloning into 'Projeto_NLP'...
remote: Enumerating objects: 202, done.
remote: Counting objects: 100% (202/202), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 202 (delta 184), reused 182 (delta 173), pack-reused 0
Receiving objects: 100% (202/202), 27.09 MiB | 17.94 MiB/s, done.
Resolving deltas: 100% (184/184), done.
Checking out files: 100% (183/183), done.


In [2]:
data = list()
services_names = set()
for path_train in ['Projeto_NLP/files/train/','Projeto_NLP/files/test/','Projeto_NLP/files/dev/']:
  for file_name in os.listdir(path_train):
    with open(path_train+file_name, 'r') as f:
      data2 = json.load(f)
      for item in data2:
        for service in item['services']:
          services_names.add(service)
        
    
      data += data2


In [3]:
#dando uma checada nos serviços do dataset
services_names

{'Alarm_1',
 'Banks_1',
 'Banks_2',
 'Buses_1',
 'Buses_2',
 'Buses_3',
 'Calendar_1',
 'Events_1',
 'Events_2',
 'Events_3',
 'Flights_1',
 'Flights_2',
 'Flights_3',
 'Flights_4',
 'Homes_1',
 'Homes_2',
 'Hotels_1',
 'Hotels_2',
 'Hotels_3',
 'Hotels_4',
 'Media_1',
 'Media_2',
 'Media_3',
 'Messaging_1',
 'Movies_1',
 'Movies_2',
 'Movies_3',
 'Music_1',
 'Music_2',
 'Music_3',
 'Payment_1',
 'RentalCars_1',
 'RentalCars_2',
 'RentalCars_3',
 'Restaurants_1',
 'Restaurants_2',
 'RideSharing_1',
 'RideSharing_2',
 'Services_1',
 'Services_2',
 'Services_3',
 'Services_4',
 'Trains_1',
 'Travel_1',
 'Weather_1'}

In [4]:
print(len(data))

22825


In [5]:
data = [item for item in data if ('Restaurants_1' in item['services'] or 'Restaurants_2' in item['services'])]

In [6]:
print(len(data))

3218


In [7]:
print(data[0])

{'dialogue_id': '60_00099', 'services': ['Events_1', 'Restaurants_1'], 'turns': [{'frames': [{'actions': [{'act': 'INFORM_INTENT', 'canonical_values': ['BuyEventTickets'], 'slot': 'intent', 'values': ['BuyEventTickets']}], 'service': 'Events_1', 'slots': [], 'state': {'active_intent': 'BuyEventTickets', 'requested_slots': [], 'slot_values': {}}}], 'speaker': 'USER', 'utterance': 'I am looking for tickets to an event.'}, {'frames': [{'actions': [{'act': 'REQUEST', 'canonical_values': [], 'slot': 'event_name', 'values': []}], 'service': 'Events_1', 'slots': []}], 'speaker': 'SYSTEM', 'utterance': 'Do you have a specific event in mind?'}, {'frames': [{'actions': [{'act': 'INFORM', 'canonical_values': ['Phutureprimitive'], 'slot': 'event_name', 'values': ['Phutureprimitive']}, {'act': 'INFORM', 'canonical_values': ['3'], 'slot': 'number_of_seats', 'values': ['3']}], 'service': 'Events_1', 'slots': [{'exclusive_end': 46, 'slot': 'event_name', 'start': 30}], 'state': {'active_intent': 'BuyEv

In [8]:
print(json.dumps(data[0], indent=4, sort_keys=True))

{
    "dialogue_id": "60_00099",
    "services": [
        "Events_1",
        "Restaurants_1"
    ],
    "turns": [
        {
            "frames": [
                {
                    "actions": [
                        {
                            "act": "INFORM_INTENT",
                            "canonical_values": [
                                "BuyEventTickets"
                            ],
                            "slot": "intent",
                            "values": [
                                "BuyEventTickets"
                            ]
                        }
                    ],
                    "service": "Events_1",
                    "slots": [],
                    "state": {
                        "active_intent": "BuyEventTickets",
                        "requested_slots": [],
                        "slot_values": {}
                    }
                }
            ],
            "speaker": "USER",
            "utterance": "I am l

In [9]:
print(json.dumps(data[0]['turns'][0], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM_INTENT",
                    "canonical_values": [
                        "BuyEventTickets"
                    ],
                    "slot": "intent",
                    "values": [
                        "BuyEventTickets"
                    ]
                }
            ],
            "service": "Events_1",
            "slots": [],
            "state": {
                "active_intent": "BuyEventTickets",
                "requested_slots": [],
                "slot_values": {}
            }
        }
    ],
    "speaker": "USER",
    "utterance": "I am looking for tickets to an event."
}


Separando um dataframe somente com os somentarios do usuarios para usarmos no na classificação de intenção

In [10]:
data3 = list()
for item in data:
  for turn in item['turns']:
    if(turn['speaker'] == 'USER'):
      #has_restaurant_frame = False
      #for frame in turn['frames']:
      #  if(frame['service'] == 'Restaurants_1' or frame['service'] == 'Restaurants_2'):
      #    has_restaurant_frame = True
      #if(has_restaurant_frame):
      data3.append(turn)
data = data3

In [11]:
print(len(data))

38465


In [12]:
print(json.dumps(data[0], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM_INTENT",
                    "canonical_values": [
                        "BuyEventTickets"
                    ],
                    "slot": "intent",
                    "values": [
                        "BuyEventTickets"
                    ]
                }
            ],
            "service": "Events_1",
            "slots": [],
            "state": {
                "active_intent": "BuyEventTickets",
                "requested_slots": [],
                "slot_values": {}
            }
        }
    ],
    "speaker": "USER",
    "utterance": "I am looking for tickets to an event."
}


In [13]:
print(json.dumps(data[1], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM",
                    "canonical_values": [
                        "Phutureprimitive"
                    ],
                    "slot": "event_name",
                    "values": [
                        "Phutureprimitive"
                    ]
                },
                {
                    "act": "INFORM",
                    "canonical_values": [
                        "3"
                    ],
                    "slot": "number_of_seats",
                    "values": [
                        "3"
                    ]
                }
            ],
            "service": "Events_1",
            "slots": [
                {
                    "exclusive_end": 46,
                    "slot": "event_name",
                    "start": 30
                }
            ],
            "state": {
                "active_intent": "BuyEventTickets",
                "

Separando somente as informações que são relacionadas ao dominio ao qual iremos trabalhar, que é o de RESTAURANTES

In [14]:
data3 = list()
for item in data:
  frame_has_restaurants = False
  for frame in item['frames']:
    if(frame['service'] == 'Restaurants_1' or frame['service'] == 'Restaurants_2'):
      frame_has_restaurants = True
  if frame_has_restaurants:
    data3.append(item)
data = data3

In [15]:
data[5]

{'frames': [{'actions': [{'act': 'INFORM',
     'canonical_values': ['moderate'],
     'slot': 'price_range',
     'values': ['moderate']},
    {'act': 'INFORM',
     'canonical_values': ['Mexican'],
     'slot': 'cuisine',
     'values': ['Tacos']},
    {'act': 'INFORM_INTENT',
     'canonical_values': ['FindRestaurants'],
     'slot': 'intent',
     'values': ['FindRestaurants']}],
   'service': 'Restaurants_1',
   'slots': [{'exclusive_end': 68, 'slot': 'cuisine', 'start': 63}],
   'state': {'active_intent': 'FindRestaurants',
    'requested_slots': [],
    'slot_values': {'city': ['Oakland'],
     'cuisine': ['Tacos'],
     'price_range': ['moderate']}}}],
 'speaker': 'USER',
 'utterance': 'Yes, I also want to find an afforadable restaurant that offers Tacos.'}

In [16]:
for item in data:
  item['frames'] = [frame for frame in item['frames'] if (frame['service'] == 'Restaurants_1' or frame['service'] == 'Restaurants_2')]

In [17]:
print(json.dumps(item, indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "THANK_YOU",
                    "canonical_values": [],
                    "slot": "",
                    "values": []
                },
                {
                    "act": "GOODBYE",
                    "canonical_values": [],
                    "slot": "",
                    "values": []
                }
            ],
            "service": "Restaurants_2",
            "slots": [],
            "state": {
                "active_intent": "ReserveRestaurant",
                "requested_slots": [],
                "slot_values": {
                    "category": [
                        "Oriental"
                    ],
                    "date": [
                        "3rd of March",
                        "day after tomorrow"
                    ],
                    "location": [
                        "Orinda"
                    ],
                    "number_o

In [18]:
print(json.dumps(data[0], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM",
                    "canonical_values": [
                        "Japanese"
                    ],
                    "slot": "cuisine",
                    "values": [
                        "Izakaya"
                    ]
                },
                {
                    "act": "INFORM_INTENT",
                    "canonical_values": [
                        "FindRestaurants"
                    ],
                    "slot": "intent",
                    "values": [
                        "FindRestaurants"
                    ]
                }
            ],
            "service": "Restaurants_1",
            "slots": [
                {
                    "exclusive_end": 61,
                    "slot": "cuisine",
                    "start": 54
                }
            ],
            "state": {
                "active_intent": "FindRestaurants",
         

Identificando os ACTIONS que estão no dataset

In [19]:
for item in data:
  #item["intent"] = item['frames'][0]['state']['active_intent']
  #item.pop('speaker', None)
  #item.pop('frames', None)
  item["intent"] = []
  for intent in item['frames'][0]['actions']:
    item["intent"] += [intent['act']]

In [20]:
for item in data:
  intents = list()
  for intent in item['intent']:
    if (intent == 'INFORM_INTENT'):
      intent = item['frames'][0]['state']['active_intent']
    intents.append(intent)
    
  item['intent'] = intents
  #print(item['intent'])

In [21]:
for item in data:
  item.pop('speaker', None)
  item.pop('frames', None)

In [22]:
data[0]

{'intent': ['INFORM', 'FindRestaurants'],
 'utterance': 'Good. I also need to find a restaurant. Are there any Izakaya places near there?'}

In [23]:
intents = set()
for item in data:
  for intent in item['intent']:
    intents.add(intent)
print(intents)
num_classes = len(intents)
print(len(intents))

{'REQUEST', 'AFFIRM', 'NEGATE', 'GOODBYE', 'SELECT', 'THANK_YOU', 'REQUEST_ALTS', 'ReserveRestaurant', 'FindRestaurants', 'AFFIRM_INTENT', 'NEGATE_INTENT', 'INFORM'}
12


In [24]:
import pandas as pd
utterances = [item['utterance'] for item in data]
df = pd.DataFrame({"utterance":utterances})

In [25]:
df

utterance
0      Good. I also need to find a restaurant. Are th...
1      Is the price range above average? What's the a...
2                                 Yes, that sounds good.
3                                   No, not now. Thanks.
4                                        No, that's all.
...                                                  ...
23419                             Ok, that will be good.
23420  Yes, I would like to reserve a table for the 3...
23421       Yes, please make it for in the evening 6:45.
23422   Yes, perfect, can you give me their user rating?
23423             Thank you, that is all I need for now.

[23424 rows x 1 columns]

In [26]:
intents

{'AFFIRM',
 'AFFIRM_INTENT',
 'FindRestaurants',
 'GOODBYE',
 'INFORM',
 'NEGATE',
 'NEGATE_INTENT',
 'REQUEST',
 'REQUEST_ALTS',
 'ReserveRestaurant',
 'SELECT',
 'THANK_YOU'}

In [27]:
for intent in intents:
  df[intent] = 0
  df['Others'] = 0
df.head()

utterance  ...  INFORM
0  Good. I also need to find a restaurant. Are th...  ...       0
1  Is the price range above average? What's the a...  ...       0
2                             Yes, that sounds good.  ...       0
3                               No, not now. Thanks.  ...       0
4                                    No, that's all.  ...       0

[5 rows x 14 columns]

In [28]:
for i in range(len(data)):
  for intent in data[i]['intent']:

    if 'FindRestaurants' in data[i]['intent']:
      df.loc[i, 'FindRestaurants'] = 1
    elif 'ReserveRestaurant' in data[i]['intent']:
      df.loc[i, 'ReserveRestaurant'] = 1
    else:
      df.loc[i, 'Others'] = 1

In [29]:
df[df['ReserveRestaurant'] == 1].head()

utterance  ...  INFORM
729                   I need a restaurant reservation.  ...       0
735  On March 2nd we are going to celebrate my wedd...  ...       0
741  id like to make a reservation for friday next ...  ...       0
746  I would like to make a reservation at the rest...  ...       0
753      I want to make a reservation at a restaurant.  ...       0

[5 rows x 14 columns]

In [30]:
df[df['Others'] != 0].head(10)

utterance  ...  INFORM
1   Is the price range above average? What's the a...  ...       0
2                              Yes, that sounds good.  ...       0
3                                No, not now. Thanks.  ...       0
4                                     No, that's all.  ...       0
6                            is alcohol served there?  ...       0
7                  Can you suggest me someplace else?  ...       0
8                  Yes, that works. That would be all  ...       0
10                                 Let's do Sicilian.  ...       0
11                                 That works for me.  ...       0
12                        Not yet, that's it for now.  ...       0

[10 rows x 14 columns]

In [31]:
df = df[['utterance','FindRestaurants','ReserveRestaurant','Others']]

In [32]:
df.head(5)

utterance  ...  Others
0  Good. I also need to find a restaurant. Are th...  ...       0
1  Is the price range above average? What's the a...  ...       1
2                             Yes, that sounds good.  ...       1
3                               No, not now. Thanks.  ...       1
4                                    No, that's all.  ...       1

[5 rows x 4 columns]

In [33]:
df.count()

utterance            23424
FindRestaurants      23424
ReserveRestaurant    23424
Others               23424
dtype: int64

In [34]:
df.sum()

utterance            Good. I also need to find a restaurant. Are th...
FindRestaurants                                                   2717
ReserveRestaurant                                                 2090
Others                                                           18617
dtype: object

Como o dataset está bem desbalanceado, precisamos fazer um reajuste nele para podermos equilibrar as coisas

In [35]:
df.head(5)

utterance  ...  Others
0  Good. I also need to find a restaurant. Are th...  ...       0
1  Is the price range above average? What's the a...  ...       1
2                             Yes, that sounds good.  ...       1
3                               No, not now. Thanks.  ...       1
4                                    No, that's all.  ...       1

[5 rows x 4 columns]

In [45]:
others = df[df['Others'] == 1]
not_others = df[df['Others'] == 0]
others = others.sample(frac = 1)
others.sum()


utterance            Yes, that would be great.I need the reservatio...
FindRestaurants                                                      0
ReserveRestaurant                                                    0
Others                                                           18617
dtype: object

In [46]:
others = others.iloc[:2500,:]
others.sum()

utterance            Yes, that would be great.I need the reservatio...
FindRestaurants                                                      0
ReserveRestaurant                                                    0
Others                                                            2500
dtype: object

In [43]:
not_others.sum()

utterance            Good. I also need to find a restaurant. Are th...
FindRestaurants                                                   2717
ReserveRestaurant                                                 2090
Others                                                               0
dtype: object

In [54]:
df = others.append(not_others)
df.sum()
df = df.sample(frac = 1)


#iniciando a classificação

In [55]:
import matplotlib.pyplot as plt
import re
import shutil
import string
import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
from tensorflow.keras import losses
from tensorflow.keras import preprocessing

In [56]:
def custom_standardization(input_data):
  lowercase = tf.strings.lower(input_data)
  stripped_html = tf.strings.regex_replace(lowercase, '<br />', ' ')
  return tf.strings.regex_replace(stripped_html,
                                  '[%s]' % re.escape(string.punctuation),
                                  '')

In [57]:
max_features = 10000
sequence_length = 250

vectorize_layer = layers.TextVectorization(
    standardize=custom_standardization,
    max_tokens=max_features,
    output_mode='int',
    output_sequence_length=sequence_length)

In [58]:
dd = df.to_dict(orient="list")

In [59]:
df

utterance  ...  Others
21477  Where can I dine with a vegetarian choices on ...  ...       0
22296                                       thanks a lot  ...       1
1256              I want a reservation for a restaurant.  ...       0
12728  I am meeting friends and would like to find a ...  ...       0
17275    I'd like to find a restaurant there too please.  ...       0
...                                                  ...  ...     ...
16208                 Yes, also do they have live music?  ...       1
5854                       I would like to eat somewhere  ...       0
22180                                         ok perfect  ...       1
14530  Oh yeah, I've heard good things about Red Joan...  ...       0
13762                     How about in the evening 7:45?  ...       1

[7307 rows x 4 columns]

Teste de vetorização de um texto

In [60]:
train_text = [x['utterance'] for x in data]
train_labels = [y['intent'] for y in data]
vectorize_layer.adapt(train_text)

In [61]:
def vectorize_text(text):
  #text = tf.expand_dims(text, -1)
  return vectorize_layer(text)

In [62]:
first_review = train_text[0]
first_label = train_labels[0]
print("Review", first_review)
#print("Label", raw_train_ds.class_names[first_label])
print("Label", first_label)
print("Vectorized review", vectorize_text(first_review))

Review Good. I also need to find a restaurant. Are there any Izakaya places near there?
Label ['INFORM', 'FindRestaurants']
Vectorized review tf.Tensor(
[ 31   3  52  42   5  17   2  12  66  16  78 295 200 207  16   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0

In [63]:
print('Vocabulary size: {}'.format(len(vectorize_layer.get_vocabulary())))

Vocabulary size: 3054


Criando a REDE

In [85]:
embedding_dim = 16

model = tf.keras.Sequential([
  layers.Embedding(max_features + 1, embedding_dim),
  layers.Dropout(0.2),
  layers.GlobalAveragePooling1D(),
  layers.Dropout(0.2),
  #layers.SpatialDropout1D(0.2),
  #layers.LSTM(200, dropout=0.2, recurrent_dropout=0.2),
  layers.Dense(50),
  layers.Dense(3, activation='softmax')])

model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, None, 16)          160016    
_________________________________________________________________
dropout_6 (Dropout)          (None, None, 16)          0         
_________________________________________________________________
global_average_pooling1d_3 ( (None, 16)                0         
_________________________________________________________________
dropout_7 (Dropout)          (None, 16)                0         
_________________________________________________________________
dense_5 (Dense)              (None, 50)                850       
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 153       
Total params: 161,019
Trainable params: 161,019
Non-trainable params: 0
________________________________________________

In [86]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [70]:
train_text = df['utterance'].tolist()
X_train = tf.convert_to_tensor([vectorize_text(utterance) for utterance in train_text])

In [71]:
X_train

<tf.Tensor: shape=(7307, 250), dtype=int64, numpy=
array([[113,  15,   3, ...,   0,   0,   0],
       [ 18,   2,  90, ...,   0,   0,   0],
       [  3,  23,   2, ...,   0,   0,   0],
       ...,
       [114,  60,   0, ...,   0,   0,   0],
       [325, 112, 345, ...,   0,   0,   0],
       [ 99, 117,  11, ...,   0,   0,   0]])>

In [72]:
Y_train = df.loc[:, df.columns != 'utterance']
Y_train = tf.convert_to_tensor(Y_train)
Y_train

<tf.Tensor: shape=(7307, 3), dtype=int64, numpy=
array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       ...,
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1]])>

In [87]:
epochs = 20
batch_size = 64

history = model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size,validation_split=0.1)

Epoch 1/20
103/103 [==============================] - 2s 10ms/step - loss: 1.0916 - accuracy: 0.3755 - val_loss: 1.0874 - val_accuracy: 0.3502
Epoch 2/20
103/103 [==============================] - 1s 8ms/step - loss: 1.0791 - accuracy: 0.4066 - val_loss: 1.0629 - val_accuracy: 0.3557
Epoch 3/20
103/103 [==============================] - 1s 8ms/step - loss: 1.0152 - accuracy: 0.5509 - val_loss: 0.9371 - val_accuracy: 0.7756
Epoch 4/20
103/103 [==============================] - 1s 8ms/step - loss: 0.8101 - accuracy: 0.7915 - val_loss: 0.6669 - val_accuracy: 0.8495
Epoch 5/20
103/103 [==============================] - 1s 8ms/step - loss: 0.5567 - accuracy: 0.8669 - val_loss: 0.4539 - val_accuracy: 0.8865
Epoch 6/20
103/103 [==============================] - 1s 8ms/step - loss: 0.4098 - accuracy: 0.8843 - val_loss: 0.3703 - val_accuracy: 0.9015
Epoch 7/20
103/103 [==============================] - 1s 8ms/step - loss: 0.3348 - accuracy: 0.9009 - val_loss: 0.3045 - val_accuracy: 0.9083
Epoch