<a href="https://colab.research.google.com/github/IndioP/Projeto_NLP/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import json
import os

data = list()
services_names = set()
for path_train in ['drive/MyDrive/NLP/train/','drive/MyDrive/NLP/test/','drive/MyDrive/NLP/dev/']:
  for file_name in os.listdir(path_train):
    with open(path_train+file_name, 'r') as f:
      data2 = json.load(f)
      for item in data2:
        for service in item['services']:
          services_names.add(service)
        
    
      data += data2


In [ ]:
#dando uma checada nos serviços do dataset
services_names

{'Alarm_1',
 'Banks_1',
 'Banks_2',
 'Buses_1',
 'Buses_2',
 'Buses_3',
 'Calendar_1',
 'Events_1',
 'Events_2',
 'Events_3',
 'Flights_1',
 'Flights_2',
 'Flights_3',
 'Flights_4',
 'Homes_1',
 'Homes_2',
 'Hotels_1',
 'Hotels_2',
 'Hotels_3',
 'Hotels_4',
 'Media_1',
 'Media_2',
 'Media_3',
 'Messaging_1',
 'Movies_1',
 'Movies_2',
 'Movies_3',
 'Music_1',
 'Music_2',
 'Music_3',
 'Payment_1',
 'RentalCars_1',
 'RentalCars_2',
 'RentalCars_3',
 'Restaurants_1',
 'Restaurants_2',
 'RideSharing_1',
 'RideSharing_2',
 'Services_1',
 'Services_2',
 'Services_3',
 'Services_4',
 'Trains_1',
 'Travel_1',
 'Weather_1'}

In [ ]:
print(len(data))

22825


In [ ]:
data = [item for item in data if ('Restaurants_1' in item['services'] or 'Restaurants_2' in item['services'])]

In [ ]:
print(len(data))

3218


In [ ]:
print(data[0])

{'dialogue_id': '111_00000', 'services': ['Events_1', 'Restaurants_1'], 'turns': [{'frames': [{'actions': [{'act': 'INFORM_INTENT', 'canonical_values': ['BuyEventTickets'], 'slot': 'intent', 'values': ['BuyEventTickets']}], 'service': 'Events_1', 'slots': [], 'state': {'active_intent': 'BuyEventTickets', 'requested_slots': [], 'slot_values': {}}}], 'speaker': 'USER', 'utterance': 'Can you help me reserve some tickets to an event?'}, {'frames': [{'actions': [{'act': 'REQUEST', 'canonical_values': [], 'slot': 'number_of_seats', 'values': []}, {'act': 'REQUEST', 'canonical_values': [], 'slot': 'date', 'values': []}, {'act': 'REQUEST', 'canonical_values': [], 'slot': 'event_name', 'values': []}], 'service': 'Events_1', 'slots': []}], 'speaker': 'SYSTEM', 'utterance': "I'll need some additional information. Do you have a certain event in mind and do you know the date you want to attend? How many tickets do you need?"}, {'frames': [{'actions': [{'act': 'INFORM', 'canonical_values': ['Remo Dr

In [ ]:
print(json.dumps(data[0], indent=4, sort_keys=True))

{
    "dialogue_id": "111_00000",
    "services": [
        "Events_1",
        "Restaurants_1"
    ],
    "turns": [
        {
            "frames": [
                {
                    "actions": [
                        {
                            "act": "INFORM_INTENT",
                            "canonical_values": [
                                "BuyEventTickets"
                            ],
                            "slot": "intent",
                            "values": [
                                "BuyEventTickets"
                            ]
                        }
                    ],
                    "service": "Events_1",
                    "slots": [],
                    "state": {
                        "active_intent": "BuyEventTickets",
                        "requested_slots": [],
                        "slot_values": {}
                    }
                }
            ],
            "speaker": "USER",
            "utterance": "Can y

In [ ]:
print(json.dumps(data[0]['turns'][0], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM_INTENT",
                    "canonical_values": [
                        "BuyEventTickets"
                    ],
                    "slot": "intent",
                    "values": [
                        "BuyEventTickets"
                    ]
                }
            ],
            "service": "Events_1",
            "slots": [],
            "state": {
                "active_intent": "BuyEventTickets",
                "requested_slots": [],
                "slot_values": {}
            }
        }
    ],
    "speaker": "USER",
    "utterance": "Can you help me reserve some tickets to an event?"
}


In [ ]:
data3 = list()
for item in data:
  for turn in item['turns']:
    if(turn['speaker'] == 'USER'):
      #has_restaurant_frame = False
      #for frame in turn['frames']:
      #  if(frame['service'] == 'Restaurants_1' or frame['service'] == 'Restaurants_2'):
      #    has_restaurant_frame = True
      #if(has_restaurant_frame):
      data3.append(turn)
data = data3

In [ ]:
print(len(data))

38465


In [ ]:
print(json.dumps(data[0], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM_INTENT",
                    "canonical_values": [
                        "BuyEventTickets"
                    ],
                    "slot": "intent",
                    "values": [
                        "BuyEventTickets"
                    ]
                }
            ],
            "service": "Events_1",
            "slots": [],
            "state": {
                "active_intent": "BuyEventTickets",
                "requested_slots": [],
                "slot_values": {}
            }
        }
    ],
    "speaker": "USER",
    "utterance": "Can you help me reserve some tickets to an event?"
}


In [ ]:
print(json.dumps(data[1], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM",
                    "canonical_values": [
                        "Remo Drive"
                    ],
                    "slot": "event_name",
                    "values": [
                        "Remo Drive"
                    ]
                },
                {
                    "act": "INFORM",
                    "canonical_values": [
                        "2"
                    ],
                    "slot": "number_of_seats",
                    "values": [
                        "2"
                    ]
                },
                {
                    "act": "INFORM",
                    "canonical_values": [
                        "2019-03-12"
                    ],
                    "slot": "date",
                    "values": [
                        "12th of this month"
                    ]
                }
            ],
            "serv

In [ ]:
data3 = list()
for item in data:
  frame_has_restaurants = False
  for frame in item['frames']:
    if(frame['service'] == 'Restaurants_1' or frame['service'] == 'Restaurants_2'):
      frame_has_restaurants = True
  if frame_has_restaurants:
    data3.append(item)
data = data3

In [ ]:
for item in data:
  item['frames'] = [frame for frame in item['frames'] if (frame['service'] == 'Restaurants_1' or frame['service'] == 'Restaurants_2')]

In [ ]:
print(json.dumps(data[0], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM_INTENT",
                    "canonical_values": [
                        "FindRestaurants"
                    ],
                    "slot": "intent",
                    "values": [
                        "FindRestaurants"
                    ]
                }
            ],
            "service": "Restaurants_1",
            "slots": [],
            "state": {
                "active_intent": "FindRestaurants",
                "requested_slots": [],
                "slot_values": {
                    "city": [
                        "San Fran",
                        "San Francisco"
                    ]
                }
            }
        }
    ],
    "speaker": "USER",
    "utterance": "Ok, that sounds fine. Can you help me find a restaurant near there too?"
}


In [ ]:
for item in data:
  #item["intent"] = item['frames'][0]['state']['active_intent']
  #item.pop('speaker', None)
  #item.pop('frames', None)
  item["intent"] = []
  for intent in item['frames'][0]['actions']:
    item["intent"] += [intent['act']]

In [ ]:
for item in data:
  intents = list()
  for intent in item['intent']:
    if (intent == 'INFORM_INTENT'):
      intent = item['frames'][0]['state']['active_intent']
    intents.append(intent)
  item['intent'] = intents
  #print(item['intent'])

In [ ]:
for item in data:
  item.pop('speaker', None)
  item.pop('frames', None)

In [ ]:
print(data)

[{'utterance': 'Ok, that sounds fine. Can you help me find a restaurant near there too?', 'intent': ['FindRestaurants']}, {'utterance': 'I think Spanish sounds great.', 'intent': ['INFORM']}, {'utterance': 'Perfect, make a reservation.', 'intent': ['ReserveRestaurant', 'SELECT']}, {'utterance': 'Do 12:15 in the afternoon.', 'intent': ['INFORM']}, {'utterance': 'Yup, that sounds good to me.', 'intent': ['AFFIRM']}, {'utterance': 'Awesome, thanks a lot.', 'intent': ['THANK_YOU']}, {'utterance': 'Nope, thanks again.', 'intent': ['NEGATE', 'THANK_YOU']}, {'utterance': 'I also need help finding restaurants in that area.', 'intent': ['FindRestaurants']}, {'utterance': "I'm really into Szcheuan food.", 'intent': ['INFORM']}, {'utterance': 'Okay, that sound good.', 'intent': ['SELECT']}, {'utterance': 'Yes, please book me a table.', 'intent': ['AFFIRM_INTENT']}, {'utterance': 'I want it for the morning 11:30.', 'intent': ['INFORM']}, {'utterance': "Yeah, that's right.", 'intent': ['AFFIRM']}, 

In [ ]:
intents = set()
for item in data:
  for intent in item['intent']:
    intents.add(intent)
print(intents)
num_classes = len(intents)
print(len(intents))

{'GOODBYE', 'AFFIRM_INTENT', 'AFFIRM', 'FindRestaurants', 'REQUEST', 'INFORM', 'SELECT', 'ReserveRestaurant', 'NEGATE', 'REQUEST_ALTS', 'NEGATE_INTENT', 'THANK_YOU'}
12


In [ ]:
import pandas as pd
utterances = [item['utterance'] for item in data]
df = pd.DataFrame({"utterance":utterances})

In [ ]:
for intent in intents:
  df[intent] = 0
df.head()

utterance  ...  THANK_YOU
0  Ok, that sounds fine. Can you help me find a r...  ...          0
1                      I think Spanish sounds great.  ...          0
2                       Perfect, make a reservation.  ...          0
3                         Do 12:15 in the afternoon.  ...          0
4                       Yup, that sounds good to me.  ...          0

[5 rows x 13 columns]

In [ ]:
for i in range(len(data)):
  for intent in data[i]['intent']:
    df.loc[i, intent] = 1

In [ ]:
df.head()

utterance  ...  THANK_YOU
0  Ok, that sounds fine. Can you help me find a r...  ...          0
1                      I think Spanish sounds great.  ...          0
2                       Perfect, make a reservation.  ...          0
3                         Do 12:15 in the afternoon.  ...          0
4                       Yup, that sounds good to me.  ...          0

[5 rows x 13 columns]

#iniciando a classificação

In [ ]:
import matplotlib.pyplot as plt
import re
import shutil
import string
import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
from tensorflow.keras import losses
from tensorflow.keras import preprocessing

In [ ]:
def custom_standardization(input_data):
  lowercase = tf.strings.lower(input_data)
  stripped_html = tf.strings.regex_replace(lowercase, '<br />', ' ')
  return tf.strings.regex_replace(stripped_html,
                                  '[%s]' % re.escape(string.punctuation),
                                  '')

In [ ]:
max_features = 10000
sequence_length = 250

vectorize_layer = layers.TextVectorization(
    standardize=custom_standardization,
    max_tokens=max_features,
    output_mode='int',
    output_sequence_length=sequence_length)

In [ ]:
train_text = [x['utterance'] for x in data]
train_labels = [y['intent'] for y in data]
vectorize_layer.adapt(train_text)

In [ ]:
def vectorize_text(text):
  #text = tf.expand_dims(text, -1)
  return vectorize_layer(text)

In [ ]:
first_review = train_text[0]
first_label = train_labels[0]
print("Review", first_review)
#print("Label", raw_train_ds.class_names[first_label])
print("Label", first_label)
print("Vectorized review", vectorize_text(first_review))

Review Ok, that sounds fine. Can you help me find a restaurant near there too?
Label ['FindRestaurants']
Vectorized review tf.Tensor(
[114   7  37  58  15   8  51  10  17   2  12 207  16 133   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

In [ ]:
print('Vocabulary size: {}'.format(len(vectorize_layer.get_vocabulary())))

Vocabulary size: 3054


In [ ]:
embedding_dim = 16

model = tf.keras.Sequential([
  layers.Embedding(max_features + 1, embedding_dim),
  #layers.Dropout(0.2),
  #layers.GlobalAveragePooling1D(),
  #layers.Dropout(0.2),
  layers.SpatialDropout1D(0.2),
  layers.LSTM(200, dropout=0.2, recurrent_dropout=0.2),
  layers.Dense(num_classes, activation='softmax')])

model.summary()

Model: "sequential_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_18 (Embedding)     (None, None, 8)           80008     
_________________________________________________________________
spatial_dropout1d_6 (Spatial (None, None, 8)           0         
_________________________________________________________________
lstm_8 (LSTM)                (None, 100)               43600     
_________________________________________________________________
dense_22 (Dense)             (None, 12)                1212      
Total params: 124,820
Trainable params: 124,820
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [ ]:
X_train = tf.convert_to_tensor([vectorize_text(utterance) for utterance in train_text])

In [ ]:
X_train

<tf.Tensor: shape=(23424, 250), dtype=int64, numpy=
array([[ 114,    7,   37, ...,    0,    0,    0],
       [   3,  150,  659, ...,    0,    0,    0],
       [  60,   27,    2, ...,    0,    0,    0],
       ...,
       [1111,  847,    7, ...,    0,    0,    0],
       [  13,    8,   33, ...,    0,    0,    0],
       [ 141,    3,  716, ...,    0,    0,    0]])>

In [ ]:
Y_train = df.loc[:, df.columns != 'utterance']
Y_train = tf.convert_to_tensor(Y_train)
Y_train

<tf.Tensor: shape=(23424, 12), dtype=int64, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]])>

In [ ]:
epochs = 10
batch_size = 64

history = model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size,validation_split=0.1)

Epoch 1/10
330/330 [==============================] - 184s 548ms/step - loss: 3.0625 - accuracy: 0.3041 - val_loss: 3.0706 - val_accuracy: 0.3026
Epoch 2/10
330/330 [==============================] - 181s 548ms/step - loss: 3.0206 - accuracy: 0.3041 - val_loss: 3.0916 - val_accuracy: 0.3026
Epoch 3/10
330/330 [==============================] - 181s 549ms/step - loss: 3.0191 - accuracy: 0.3041 - val_loss: 3.0728 - val_accuracy: 0.3026
Epoch 4/10
141/330 [===========>..................] - ETA: 1:42 - loss: 3.0346 - accuracy: 0.3031

KeyboardInterrupt: ignored