In [108]:
import json
import os

data = list()
services_names = set()
for path_train in ['Projeto_NLP/files/train/','Projeto_NLP/files/test/','Projeto_NLP/files/dev/']:
  for file_name in os.listdir(path_train):
    with open(path_train+file_name, 'r') as f:
      data2 = json.load(f)
      for item in data2:
        for service in item['services']:
          services_names.add(service)
        
    
      data += data2


In [109]:
#dando uma checada nos serviços do dataset
services_names

{'Alarm_1',
 'Banks_1',
 'Banks_2',
 'Buses_1',
 'Buses_2',
 'Buses_3',
 'Calendar_1',
 'Events_1',
 'Events_2',
 'Events_3',
 'Flights_1',
 'Flights_2',
 'Flights_3',
 'Flights_4',
 'Homes_1',
 'Homes_2',
 'Hotels_1',
 'Hotels_2',
 'Hotels_3',
 'Hotels_4',
 'Media_1',
 'Media_2',
 'Media_3',
 'Messaging_1',
 'Movies_1',
 'Movies_2',
 'Movies_3',
 'Music_1',
 'Music_2',
 'Music_3',
 'Payment_1',
 'RentalCars_1',
 'RentalCars_2',
 'RentalCars_3',
 'Restaurants_1',
 'Restaurants_2',
 'RideSharing_1',
 'RideSharing_2',
 'Services_1',
 'Services_2',
 'Services_3',
 'Services_4',
 'Trains_1',
 'Travel_1',
 'Weather_1'}

In [110]:
print(len(data))

22825


In [111]:
data = [item for item in data if ('Restaurants_1' in item['services'] or 'Restaurants_2' in item['services'])]

In [112]:
print(len(data))

3218


In [113]:
print(data[0])

{'dialogue_id': '45_00071', 'services': ['Weather_1', 'Restaurants_1'], 'turns': [{'frames': [{'actions': [{'act': 'INFORM', 'canonical_values': ['2019-03-07'], 'slot': 'date', 'values': ['March 7th']}, {'act': 'INFORM_INTENT', 'canonical_values': ['GetWeather'], 'slot': 'intent', 'values': ['GetWeather']}], 'service': 'Weather_1', 'slots': [{'exclusive_end': 41, 'slot': 'date', 'start': 32}], 'state': {'active_intent': 'GetWeather', 'requested_slots': [], 'slot_values': {'date': ['March 7th']}}}], 'speaker': 'USER', 'utterance': 'I want to check the weather for March 7th.'}, {'frames': [{'actions': [{'act': 'REQUEST', 'canonical_values': [], 'slot': 'city', 'values': []}], 'service': 'Weather_1', 'slots': []}], 'speaker': 'SYSTEM', 'utterance': 'What city are you checking the weather for?'}, {'frames': [{'actions': [{'act': 'INFORM', 'canonical_values': ['Dixon'], 'slot': 'city', 'values': ['Dixon']}], 'service': 'Weather_1', 'slots': [{'exclusive_end': 24, 'slot': 'city', 'start': 19

In [114]:
print(json.dumps(data[0], indent=4, sort_keys=True))

{
    "dialogue_id": "45_00071",
    "services": [
        "Weather_1",
        "Restaurants_1"
    ],
    "turns": [
        {
            "frames": [
                {
                    "actions": [
                        {
                            "act": "INFORM",
                            "canonical_values": [
                                "2019-03-07"
                            ],
                            "slot": "date",
                            "values": [
                                "March 7th"
                            ]
                        },
                        {
                            "act": "INFORM_INTENT",
                            "canonical_values": [
                                "GetWeather"
                            ],
                            "slot": "intent",
                            "values": [
                                "GetWeather"
                            ]
                        }
                    ],
 

In [115]:
print(json.dumps(data[0]['turns'][0], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM",
                    "canonical_values": [
                        "2019-03-07"
                    ],
                    "slot": "date",
                    "values": [
                        "March 7th"
                    ]
                },
                {
                    "act": "INFORM_INTENT",
                    "canonical_values": [
                        "GetWeather"
                    ],
                    "slot": "intent",
                    "values": [
                        "GetWeather"
                    ]
                }
            ],
            "service": "Weather_1",
            "slots": [
                {
                    "exclusive_end": 41,
                    "slot": "date",
                    "start": 32
                }
            ],
            "state": {
                "active_intent": "GetWeather",
                "requested_slo

In [116]:
data3 = list()
for item in data:
  for turn in item['turns']:
    if(turn['speaker'] == 'USER'):
      #has_restaurant_frame = False
      #for frame in turn['frames']:
      #  if(frame['service'] == 'Restaurants_1' or frame['service'] == 'Restaurants_2'):
      #    has_restaurant_frame = True
      #if(has_restaurant_frame):
      data3.append(turn)
data = data3

In [117]:
print(len(data))

38465


In [118]:
print(json.dumps(data[0], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM",
                    "canonical_values": [
                        "2019-03-07"
                    ],
                    "slot": "date",
                    "values": [
                        "March 7th"
                    ]
                },
                {
                    "act": "INFORM_INTENT",
                    "canonical_values": [
                        "GetWeather"
                    ],
                    "slot": "intent",
                    "values": [
                        "GetWeather"
                    ]
                }
            ],
            "service": "Weather_1",
            "slots": [
                {
                    "exclusive_end": 41,
                    "slot": "date",
                    "start": 32
                }
            ],
            "state": {
                "active_intent": "GetWeather",
                "requested_slo

In [119]:
print(json.dumps(data[1], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM",
                    "canonical_values": [
                        "Dixon"
                    ],
                    "slot": "city",
                    "values": [
                        "Dixon"
                    ]
                }
            ],
            "service": "Weather_1",
            "slots": [
                {
                    "exclusive_end": 24,
                    "slot": "city",
                    "start": 19
                }
            ],
            "state": {
                "active_intent": "GetWeather",
                "requested_slots": [],
                "slot_values": {
                    "city": [
                        "Dixon"
                    ],
                    "date": [
                        "March 7th"
                    ]
                }
            }
        }
    ],
    "speaker": "USER",
    "utterance": "I want to check 

In [120]:
data3 = list()
for item in data:
  frame_has_restaurants = False
  for frame in item['frames']:
    if(frame['service'] == 'Restaurants_1' or frame['service'] == 'Restaurants_2'):
      frame_has_restaurants = True
  if frame_has_restaurants:
    data3.append(item)
data = data3

In [121]:
for item in data:
  item['frames'] = [frame for frame in item['frames'] if (frame['service'] == 'Restaurants_1' or frame['service'] == 'Restaurants_2')]

In [122]:
print(json.dumps(data[0], indent=4, sort_keys=True))

{
    "frames": [
        {
            "actions": [
                {
                    "act": "INFORM_INTENT",
                    "canonical_values": [
                        "FindRestaurants"
                    ],
                    "slot": "intent",
                    "values": [
                        "FindRestaurants"
                    ]
                }
            ],
            "service": "Restaurants_1",
            "slots": [],
            "state": {
                "active_intent": "FindRestaurants",
                "requested_slots": [],
                "slot_values": {
                    "city": [
                        "Dixon"
                    ]
                }
            }
        }
    ],
    "speaker": "USER",
    "utterance": "Okay. I want to find a restaurant, as well."
}


In [123]:
for item in data:
  #item["intent"] = item['frames'][0]['state']['active_intent']
  #item.pop('speaker', None)
  #item.pop('frames', None)
  item["intent"] = []
  for intent in item['frames'][0]['actions']:
    item["intent"] += [intent['act']]

In [124]:
for item in data:
  intents = list()
  for intent in item['intent']:
    if (intent == 'INFORM_INTENT'):
      intent = item['frames'][0]['state']['active_intent']
    intents.append(intent)
  item['intent'] = intents
  #print(item['intent'])

In [125]:
for item in data:
  item.pop('speaker', None)
  item.pop('frames', None)

In [126]:
data[0]

{'intent': ['FindRestaurants'],
 'utterance': 'Okay. I want to find a restaurant, as well.'}

In [127]:
intents = set()
for item in data:
  for intent in item['intent']:
    intents.add(intent)
print(intents)
num_classes = len(intents)
print(len(intents))

{'REQUEST_ALTS', 'AFFIRM', 'FindRestaurants', 'REQUEST', 'INFORM', 'SELECT', 'NEGATE_INTENT', 'AFFIRM_INTENT', 'THANK_YOU', 'ReserveRestaurant', 'NEGATE', 'GOODBYE'}
12


In [128]:
import pandas as pd
utterances = [item['utterance'] for item in data]
df = pd.DataFrame({"utterance":utterances})

In [129]:
df

utterance
0            Okay. I want to find a restaurant, as well.
1      I want to go somewhere that serves alcohol. As...
2                                   What is the address?
3         Is there live music? What is the phone number?
4                                   Sounds good, thanks.
...                                                  ...
23419     Reserve a table at 1 o"clock in the afternoon.
23420               Make that table for four at 7:30 pm.
23421                                              Nice.
23422                                            Thanks.
23423                                That's all. Thanks.

[23424 rows x 1 columns]

In [130]:
intents

{'AFFIRM',
 'AFFIRM_INTENT',
 'FindRestaurants',
 'GOODBYE',
 'INFORM',
 'NEGATE',
 'NEGATE_INTENT',
 'REQUEST',
 'REQUEST_ALTS',
 'ReserveRestaurant',
 'SELECT',
 'THANK_YOU'}

In [132]:
for intent in intents:
  df[intent] = 0
  df['Others'] = 0
df.head()

utterance  ...  Others
0        Okay. I want to find a restaurant, as well.  ...       0
1  I want to go somewhere that serves alcohol. As...  ...       0
2                               What is the address?  ...       0
3     Is there live music? What is the phone number?  ...       0
4                               Sounds good, thanks.  ...       0

[5 rows x 14 columns]

In [139]:
for i in range(len(data)):
  for intent in data[i]['intent']:
    #print(intent)
    if intent not in ['FindRestaurants','ReserveRestaurant']:
      #print('1 - ',intent)
      df.loc[i, 'Others'] = 1
      df.loc[i, intent] = 1
    else:
      #print('2 - ',intent)
      df.loc[i, intent] = 1
    #df.loc[i, intent] = 1

In [140]:
df.head()

utterance  ...  Others
0        Okay. I want to find a restaurant, as well.  ...       0
1  I want to go somewhere that serves alcohol. As...  ...       1
2                               What is the address?  ...       1
3     Is there live music? What is the phone number?  ...       1
4                               Sounds good, thanks.  ...       1

[5 rows x 14 columns]

In [142]:
df[df['Others'] != 0].head(10)

utterance  ...  Others
1   I want to go somewhere that serves alcohol. As...  ...       1
2                                What is the address?  ...       1
3      Is there live music? What is the phone number?  ...       1
4                                Sounds good, thanks.  ...       1
5                   Yes I want to make a reservation.  ...       1
6   I want to make it for half past 11 in the morn...  ...       1
7                     Yes, sounds good. Is it pricey?  ...       1
8                                     Thanks so much.  ...       1
9                                     No, that's all.  ...       1
10           ok, please find me a barbecue restaurant  ...       1

[10 rows x 14 columns]

In [143]:
df = df[['utterance','FindRestaurants','ReserveRestaurant','Others']]

In [144]:
df.head(5)

utterance  ...  Others
0        Okay. I want to find a restaurant, as well.  ...       0
1  I want to go somewhere that serves alcohol. As...  ...       1
2                               What is the address?  ...       1
3     Is there live music? What is the phone number?  ...       1
4                               Sounds good, thanks.  ...       1

[5 rows x 4 columns]

#iniciando a classificação

In [145]:
import matplotlib.pyplot as plt
import re
import shutil
import string
import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
from tensorflow.keras import losses
from tensorflow.keras import preprocessing

In [146]:
def custom_standardization(input_data):
  lowercase = tf.strings.lower(input_data)
  stripped_html = tf.strings.regex_replace(lowercase, '<br />', ' ')
  return tf.strings.regex_replace(stripped_html,
                                  '[%s]' % re.escape(string.punctuation),
                                  '')

In [147]:
max_features = 10000
sequence_length = 250

vectorize_layer = layers.TextVectorization(
    standardize=custom_standardization,
    max_tokens=max_features,
    output_mode='int',
    output_sequence_length=sequence_length)

In [148]:
train_text = [x['utterance'] for x in data]
train_labels = [y['intent'] for y in data]
vectorize_layer.adapt(train_text)

In [149]:
def vectorize_text(text):
  #text = tf.expand_dims(text, -1)
  return vectorize_layer(text)

In [150]:
first_review = train_text[0]
first_label = train_labels[0]
print("Review", first_review)
#print("Label", raw_train_ds.class_names[first_label])
print("Label", first_label)
print("Vectorized review", vectorize_text(first_review))

Review Okay. I want to find a restaurant, as well.
Label ['FindRestaurants']
Vectorized review tf.Tensor(
[ 65   3  23   5  17   2  12 180 141   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0  

In [151]:
print('Vocabulary size: {}'.format(len(vectorize_layer.get_vocabulary())))

Vocabulary size: 3054


In [152]:
embedding_dim = 16

model = tf.keras.Sequential([
  layers.Embedding(max_features + 1, embedding_dim),
  #layers.Dropout(0.2),
  #layers.GlobalAveragePooling1D(),
  #layers.Dropout(0.2),
  layers.SpatialDropout1D(0.2),
  layers.LSTM(200, dropout=0.2, recurrent_dropout=0.2),
  layers.Dense(3, activation='softmax')])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 16)          160016    
_________________________________________________________________
spatial_dropout1d (SpatialDr (None, None, 16)          0         
_________________________________________________________________
lstm (LSTM)                  (None, 200)               173600    
_________________________________________________________________
dense (Dense)                (None, 3)                 603       
Total params: 334,219
Trainable params: 334,219
Non-trainable params: 0
_________________________________________________________________


In [153]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [154]:
X_train = tf.convert_to_tensor([vectorize_text(utterance) for utterance in train_text])

In [155]:
X_train

<tf.Tensor: shape=(23424, 250), dtype=int64, numpy=
array([[ 65,   3,  23, ...,   0,   0,   0],
       [  3,  23,   5, ...,   0,   0,   0],
       [ 39,   9,   6, ...,   0,   0,   0],
       ...,
       [121,   0,   0, ...,   0,   0,   0],
       [ 18,   0,   0, ...,   0,   0,   0],
       [ 29,  41,  18, ...,   0,   0,   0]])>

In [156]:
Y_train = df.loc[:, df.columns != 'utterance']
Y_train = tf.convert_to_tensor(Y_train)
Y_train

<tf.Tensor: shape=(23424, 3), dtype=int64, numpy=
array([[1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       ...,
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])>

In [ ]:
epochs = 10
batch_size = 64

history = model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size,validation_split=0.1)

Epoch 1/10
330/330 [==============================] - 184s 548ms/step - loss: 3.0625 - accuracy: 0.3041 - val_loss: 3.0706 - val_accuracy: 0.3026
Epoch 2/10
330/330 [==============================] - 181s 548ms/step - loss: 3.0206 - accuracy: 0.3041 - val_loss: 3.0916 - val_accuracy: 0.3026
Epoch 3/10
330/330 [==============================] - 181s 549ms/step - loss: 3.0191 - accuracy: 0.3041 - val_loss: 3.0728 - val_accuracy: 0.3026
Epoch 4/10
141/330 [===========>..................] - ETA: 1:42 - loss: 3.0346 - accuracy: 0.3031

KeyboardInterrupt: ignored

In [157]:
epochs = 10
batch_size = 64

history = model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size,validation_split=0.1)

Epoch 1/10
330/330 [==============================] - 444s 1s/step - loss: 0.7081 - accuracy: 0.7913 - val_loss: 0.6842 - val_accuracy: 0.8007
Epoch 2/10
330/330 [==============================] - 440s 1s/step - loss: 0.6934 - accuracy: 0.7941 - val_loss: 0.6726 - val_accuracy: 0.8007
Epoch 3/10
330/330 [==============================] - 440s 1s/step - loss: 0.6939 - accuracy: 0.7941 - val_loss: 0.6705 - val_accuracy: 0.8007
Epoch 4/10
330/330 [==============================] - 441s 1s/step - loss: 0.6947 - accuracy: 0.7941 - val_loss: 0.6656 - val_accuracy: 0.8007
Epoch 5/10
330/330 [==============================] - 442s 1s/step - loss: 0.6953 - accuracy: 0.7941 - val_loss: 0.6599 - val_accuracy: 0.8007
Epoch 6/10
330/330 [==============================] - 443s 1s/step - loss: 0.6935 - accuracy: 0.7941 - val_loss: 0.6609 - val_accuracy: 0.8007
Epoch 7/10
330/330 [==============================] - 439s 1s/step - loss: 0.6954 - accuracy: 0.7941 - val_loss: 0.6812 - val_accuracy: 0.8007